spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_up
    username: root
    password: Infinito12-
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
fileRepositoryFolder: C:\ex springBoot\Servizi-FileUpload